// Mocks generated by Mockito 5.1.0 from annotations
// in helios_q1/test/src/features/settings/data/repositories/settings_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i4;
import 'package:helios_q1/src/features/settings/data/data_sources/settings_local_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SettingsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsLocalDataSource extends _i1.Mock
    implements _i2.SettingsLocalDataSource {
  MockSettingsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ThemeMode> getLastThemeMode() =>
      (super.noSuchMethod(Invocation.method(#getLastThemeMode, []),
              returnValue: Future<_i4.ThemeMode>.value(_i4.ThemeMode.system))
          as _i3.Future<_i4.ThemeMode>);
  @override
  _i3.Future<void> cacheThemeMode(_i4.ThemeMode? themeMode) =>
      (super.noSuchMethod(Invocation.method(#cacheThemeMode, [themeMode]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
