name: helios_q1
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  internet_connection_checker: ^0.0.1+3
  fpdart: ^0.0.12
  get_it: ^7.2.0
  flutter_typeahead: ^3.2.4
  shimmer: ^2.0.0
  dio: ^4.0.4
  shared_preferences: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.16
  build_runner: ^2.1.5
  bloc_test: ^9.0.0
  test: ^1.19.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
